### PR TITLE
Added some people to the list!

### PR DESCRIPTION
**Pull request by RDIL**
Added from #8 and #1.

### CODE REVIEW

**Comment by PelajTech** [comment]
Considering nothing here implies that I skid, I request my name be removed.

Or, you know, provide, iunno, evidence?

**Comment by RDIL** [comment]
Idk

**Comment by PelajTech** [comment]
oh well joel is a skid himself so tOucHe

**Comment by RDIL** [comment]
OOF

**Comment by RDIL** [comment]
Pls merge PR k thx

**Comment by RDIL** [comment]
Added from #4

**Comment by PelajTech** [comment]
> > oh well joel is a skid himself so tOucHe
> 
> says you dog shit unpaid retard

you're just mad your code is shit :b:uddy :b:oy. You don't know how generics work, where the fuck is your name? As alex said: Underlined and bolded, not crossed out.

**Comment by RDIL** [comment]
the green button is ready to be pressed, you guys should have this discussion in an issue

**Comment by PelajTech** [comment]
> the green button is ready to be pressed, you guys should have this discussion in an issue

No? Cause you re-added me to this shitty list. Either provide proof or fuck off.

**Comment by RDIL** [comment]
... i never readded u

**Pull request closed without merging**
